/* eslint-disable @next/next/no-css-tags */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";
import Header from "../components/header/Header";
import Introduction from "../components/introduction/Introduction";
import Movetojourney from "../components/movetojourney/Movetojourney";
import styles from "../styles/Home.module.css";

export default function Home1() {
  const [current, setCurrent] = useState(0);
  const [wait, setWait] = useState(false);

  return (
    <div className={styles.container1}>
      <Head>
        <title>Shutterstock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="/fonts/font-awesome/css/font-awesome.css"
        />
      </Head>
      <div className="headerStyle">
        <Header />
      </div>
      <AnimatePresence>
        <motion.main
          className={styles.main}
          onClick={() => {
            setCurrent(current + 1);
          }}
        >
          <div className={styles.mainContent}>
            <Introduction />
            <Movetojourney />
            <motion.div
              className={styles.earth}
              initial={{ y: 1000, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              exit={{ y: -10, opacity: 0 }}
              transition={{ duration: 2.5 }}
            >
              <img src="/assets/image/earth.png" alt="earth" />
            </motion.div>
          </div>
        </motion.main>
      </AnimatePresence>

      <motion.div
        className={styles.social}
        initial={{ y: 1000, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        exit={{ y: -10, opacity: 0 }}
        transition={{ duration: 2.5 }}
      >
        <img
          className={styles.socialBtn}
          src="/assets/image/instagram.png"
          alt=""
        />
        <img
          className={styles.socialBtn}
          src="/assets/image/Twitter.png"
          alt=""
        />
        <img
          className={styles.socialBtn}
          src="/assets/image/Discord.png"
          alt=""
        />
      </motion.div>
    </div>
  );
}
