/* eslint-disable @next/next/no-css-tags */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";

import Header from "../components/header/Header";
import NFTcard from "../components/NFTcards/NFTcard";
import cardDatas from "../lib/cyberLife.json";
import styles from "../styles/Home.module.css";

export default function Home3() {
  const [nftCardData, setCardData] = useState([]);
  useEffect(() => {
    setCardData(cardDatas);
  }, []);
  console.log("this i scalling", nftCardData.cardDatas);

  return (
    <div className={styles.container3}>
      <Head>
        <title>Shutterstock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="/fonts/font-awesome/css/font-awesome.css"
        />
      </Head>
      <div className="headerStyle">
        <Header />
      </div>
      <main className={styles.main}>
        <div className={styles.mainContent}>
          <div className="p-8 lg:p-8 xl:p-16 2xl:p-20 mt-8">
            <div className={styles.investorBar}>
              {/* <div className="flex justify-around flex-wrap"> */}
              <span className={styles.investorTitle}>Investor Collection</span>
              <div className={styles.selectList}></div>
              {/* </div> */}
            </div>
          </div>
          <div className="p-8 lg:p-8 xl:p-16 2xl:p-20 mt-8">
            <div className={styles.NFTCollection}>
              <div className="m-12">
                <div className="flex justify-around flex-wrap">
                  {nftCardData.cardDatas
                    ? nftCardData.cardDatas.map((items, i) => (
                      <NFTcard
                        cardData={items}
                        key={`${items.imgAlt1}-${i}`}
                      />
                    ))
                    : "Loading..."}
                </div>
              </div>
            </div>
          </div>
          {/* <motion.h1
            className={styles.collectiontitle}
            initial={{ y: 1000, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: -10, opacity: 0 }}
            transition={{ duration: 2.5 }}
          >
            Choose Collection
          </motion.h1>

          <motion.div
            className={styles.collections}
            initial={{ y: 1000, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: -10, opacity: 0 }}
            transition={{ duration: 2.5 }}
          >
            <div className="flex justify-around flex-wrap p-1 sm:p-20">
              <div className="m-8">
                <CollectionCard className="p-8" />
              </div>
              <div className="m-8">
                <InvestorCard className="p-8" />
              </div>
            </div>
          </motion.div> */}
        </div>
      </main>
      <style jsx>{``}</style>
    </div>
  );
}
