/* eslint-disable @next/next/no-css-tags */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { motion, AnimatePresence } from "framer-motion";

import CollectionCard from "../components/collectionCard/CollectionCard";
import Header from "../components/header/Header";
import InvestorCard from "../components/investorCard/InvestorCard";
import styles from "../styles/Home.module.css";

export default function Home2() {
  return (
    <div className={styles.container2}>
      <Head>
        <title>Shutterstock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="/fonts/font-awesome/css/font-awesome.css"
        />
      </Head>
      <div className="headerStyle">
        <Header />
      </div>
      <main className={styles.main}>
        <div className={styles.mainContent}>
          <motion.h1
            className={styles.collectiontitle}
            initial={{ y: 1000, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: -10, opacity: 0 }}
            transition={{ duration: 2.5 }}
          >
            Choose Collection
          </motion.h1>

          <motion.div
            className={styles.collections}
            initial={{ y: 1000, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: -10, opacity: 0 }}
            transition={{ duration: 2.5 }}
          >
            <div className="flex justify-around flex-wrap p-1 sm:p-20">
              <div className="m-8">
                <CollectionCard className="p-8" />
              </div>
              <div className="m-8">
                <InvestorCard className="p-8" />
              </div>
            </div>
          </motion.div>
        </div>
      </main>
    </div>
  );
}
